version: '2'
services:
  dev:
    image: node:11
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run start"
    ports:
      - 3000:3000
      - 8080:8080